"""Emit the PostgreSQL DDL for the current models into migrations/001_initial.sql.
The app also runs `create_all` on start, so SQLite needs no migration step."""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from sqlalchemy.dialects import postgresql  # noqa: E402
from sqlalchemy.schema import CreateIndex, CreateTable  # noqa: E402

from app.persistence.models import Base  # noqa: E402


def main() -> None:
    out = ["-- Generated by scripts/export_schema.py from backend/app/persistence/models.py. Do not edit by hand.", "BEGIN;", ""]
    for table in Base.metadata.sorted_tables:
        out.append(str(CreateTable(table).compile(dialect=postgresql.dialect())).strip() + ";")
        for index in table.indexes:
            out.append(str(CreateIndex(index).compile(dialect=postgresql.dialect())).strip() + ";")
        out.append("")
    out.append("COMMIT;")
    target = ROOT / "migrations" / "001_initial.sql"
    target.write_text("\n".join(out) + "\n")
    print(f"wrote {target}")


if __name__ == "__main__":
    main()
