
CREATE TABLE IF NOT EXISTS customers (id TEXT PRIMARY KEY, version INTEGER NOT NULL, data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS events (id INTEGER PRIMARY KEY AUTOINCREMENT, customer_id TEXT NOT NULL, case_id TEXT, event_type TEXT NOT NULL, actor TEXT NOT NULL, occurred_at TEXT NOT NULL, data TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_events_customer ON events(customer_id, id);
CREATE TABLE IF NOT EXISTS outbox (id INTEGER PRIMARY KEY AUTOINCREMENT, event_id INTEGER UNIQUE NOT NULL, delivered INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS jobs (id TEXT PRIMARY KEY, customer_id TEXT NOT NULL, proposal_id TEXT NOT NULL, status TEXT NOT NULL, lease_until REAL NOT NULL DEFAULT 0, available_at REAL NOT NULL DEFAULT 0, attempts INTEGER NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS idx_jobs_status ON jobs(status, available_at, lease_until);
CREATE TABLE IF NOT EXISTS inbox (provider TEXT NOT NULL, event_id TEXT NOT NULL, data TEXT NOT NULL, PRIMARY KEY(provider,event_id));
CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY, expires REAL NOT NULL);
CREATE TABLE IF NOT EXISTS tool_runs (id INTEGER PRIMARY KEY AUTOINCREMENT, customer_id TEXT NOT NULL, name TEXT NOT NULL, at TEXT NOT NULL, outcome TEXT NOT NULL);
