"""Generate migrations/0001_initial.sql for PostgreSQL from the SQLAlchemy models.

Usage: python scripts/dump_schema.py > migrations/0001_initial.sql
The SQL is generated from the models so the two cannot drift.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from sqlalchemy.dialects import postgresql  # noqa: E402
from sqlalchemy.schema import CreateIndex, CreateTable  # noqa: E402

from backend.app.persistence import models  # noqa: E402,F401
from backend.app.persistence.db import Base  # noqa: E402


def main() -> None:
    dialect = postgresql.dialect()
    out = ["-- Generated by scripts/dump_schema.py from backend/app/persistence/models.py", "-- Target: PostgreSQL. Apply with: psql \"$DATABASE_URL\" -f migrations/0001_initial.sql", "BEGIN;", ""]
    for table in Base.metadata.sorted_tables:
        out.append(str(CreateTable(table).compile(dialect=dialect)).strip() + ";")
        for index in table.indexes:
            out.append(str(CreateIndex(index).compile(dialect=dialect)).strip() + ";")
        out.append("")
    out.append("COMMIT;")
    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
