-- Generated by scripts/dump_schema.py from backend/app/persistence/models.py
-- Target: PostgreSQL. Apply with: psql "$DATABASE_URL" -f migrations/0001_initial.sql
BEGIN;

CREATE TABLE customers (
	id VARCHAR(64) NOT NULL, 
	tenant_id VARCHAR(64) NOT NULL, 
	display_name VARCHAR(200) NOT NULL, 
	api_token_hash VARCHAR(128) NOT NULL, 
	verified_facts_json JSON NOT NULL, 
	property_json JSON NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (api_token_hash)
);
CREATE INDEX ix_customers_tenant_id ON customers (tenant_id);

CREATE TABLE jobs (
	id VARCHAR(64) NOT NULL, 
	type VARCHAR(48) NOT NULL, 
	case_id VARCHAR(64), 
	payload_json JSON NOT NULL, 
	status VARCHAR(16) NOT NULL, 
	run_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	lease_owner VARCHAR(64), 
	lease_until TIMESTAMP WITHOUT TIME ZONE, 
	attempts INTEGER NOT NULL, 
	max_attempts INTEGER NOT NULL, 
	last_error TEXT, 
	dedupe_key VARCHAR(128), 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (dedupe_key)
);
CREATE INDEX ix_jobs_run_at ON jobs (run_at);
CREATE INDEX ix_jobs_status_run_at ON jobs (status, run_at);
CREATE INDEX ix_jobs_status ON jobs (status);
CREATE INDEX ix_jobs_case_id ON jobs (case_id);
CREATE INDEX ix_jobs_type ON jobs (type);

CREATE TABLE outbox (
	id VARCHAR(64) NOT NULL, 
	topic VARCHAR(64) NOT NULL, 
	payload_json JSON NOT NULL, 
	signature VARCHAR(128) NOT NULL, 
	status VARCHAR(16) NOT NULL, 
	attempts INTEGER NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	delivered_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
);
CREATE INDEX ix_outbox_status ON outbox (status);
CREATE INDEX ix_outbox_topic ON outbox (topic);

CREATE TABLE provider_events (
	id VARCHAR(64) NOT NULL, 
	provider VARCHAR(64) NOT NULL, 
	provider_event_id VARCHAR(128) NOT NULL, 
	event_type VARCHAR(64) NOT NULL, 
	case_id VARCHAR(64), 
	payload_json JSON NOT NULL, 
	status VARCHAR(16) NOT NULL, 
	received_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	processed_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_provider_event UNIQUE (provider, provider_event_id)
);

CREATE TABLE tool_runs (
	id VARCHAR(64) NOT NULL, 
	case_id VARCHAR(64), 
	tool_name VARCHAR(64) NOT NULL, 
	input_ref TEXT NOT NULL, 
	output_ref TEXT NOT NULL, 
	source VARCHAR(64) NOT NULL, 
	authority VARCHAR(16) NOT NULL, 
	source_timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	latency_ms INTEGER NOT NULL, 
	model_version VARCHAR(64) NOT NULL, 
	prompt_version VARCHAR(64) NOT NULL, 
	outcome VARCHAR(32) NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);
CREATE INDEX ix_tool_runs_case_id ON tool_runs (case_id);

CREATE TABLE documents (
	id VARCHAR(64) NOT NULL, 
	owner_customer_id VARCHAR(64) NOT NULL, 
	kind VARCHAR(64) NOT NULL, 
	object_key VARCHAR(256) NOT NULL, 
	content_hash VARCHAR(128) NOT NULL, 
	source VARCHAR(32) NOT NULL, 
	captured_at TIMESTAMP WITHOUT TIME ZONE, 
	extraction_version VARCHAR(32) NOT NULL, 
	content_json JSON NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(owner_customer_id) REFERENCES customers (id)
);
CREATE INDEX ix_documents_owner_customer_id ON documents (owner_customer_id);

CREATE TABLE mortgages (
	id VARCHAR(64) NOT NULL, 
	customer_id VARCHAR(64) NOT NULL, 
	currency VARCHAR(3) NOT NULL, 
	balance_minor INTEGER NOT NULL, 
	note_rate_decimal VARCHAR(16) NOT NULL, 
	remaining_months INTEGER NOT NULL, 
	monthly_pi_minor INTEGER, 
	escrow_minor INTEGER NOT NULL, 
	payment_includes_escrow BOOLEAN, 
	as_of TIMESTAMP WITHOUT TIME ZONE, 
	evidence_id VARCHAR(64), 
	servicer_lender_id VARCHAR(64), 
	balance_confirmed_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(customer_id) REFERENCES customers (id)
);
CREATE INDEX ix_mortgages_customer_id ON mortgages (customer_id);

CREATE TABLE cases (
	id VARCHAR(64) NOT NULL, 
	tenant_id VARCHAR(64) NOT NULL, 
	customer_id VARCHAR(64) NOT NULL, 
	workflow_type VARCHAR(64) NOT NULL, 
	mortgage_id VARCHAR(64) NOT NULL, 
	state VARCHAR(48) NOT NULL, 
	version INTEGER NOT NULL, 
	holding_horizon_months INTEGER, 
	maximum_cash_to_close_minor INTEGER, 
	finance_costs_json JSON NOT NULL, 
	missing_fields_json JSON NOT NULL, 
	outstanding_questions_json JSON NOT NULL, 
	selected_offer_id VARCHAR(64), 
	latest_comparison_id VARCHAR(64), 
	completion_evidence_ref VARCHAR(128), 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(customer_id) REFERENCES customers (id), 
	FOREIGN KEY(mortgage_id) REFERENCES mortgages (id)
);
CREATE INDEX ix_cases_tenant_id ON cases (tenant_id);
CREATE INDEX ix_cases_customer_id ON cases (customer_id);
CREATE INDEX ix_cases_state ON cases (state);

CREATE TABLE actions (
	id VARCHAR(64) NOT NULL, 
	case_id VARCHAR(64) NOT NULL, 
	type VARCHAR(48) NOT NULL, 
	payload_json JSON NOT NULL, 
	payload_hash VARCHAR(128) NOT NULL, 
	status VARCHAR(32) NOT NULL, 
	approval_id VARCHAR(64), 
	provider_reference VARCHAR(128), 
	idempotency_key VARCHAR(128) NOT NULL, 
	client_request_ref VARCHAR(128) NOT NULL, 
	review_json JSON NOT NULL, 
	result_json JSON NOT NULL, 
	bound_case_version INTEGER NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_actions_case_idem UNIQUE (case_id, idempotency_key), 
	FOREIGN KEY(case_id) REFERENCES cases (id), 
	UNIQUE (client_request_ref)
);
CREATE INDEX ix_actions_status ON actions (status);
CREATE INDEX ix_actions_case_id ON actions (case_id);

CREATE TABLE case_events (
	id VARCHAR(64) NOT NULL, 
	case_id VARCHAR(64) NOT NULL, 
	sequence INTEGER NOT NULL, 
	event_type VARCHAR(64) NOT NULL, 
	source_event_id VARCHAR(128), 
	actor VARCHAR(64) NOT NULL, 
	previous_state VARCHAR(48), 
	next_state VARCHAR(48), 
	expected_case_version INTEGER, 
	data_json JSON NOT NULL, 
	occurred_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_case_events_seq UNIQUE (case_id, sequence), 
	FOREIGN KEY(case_id) REFERENCES cases (id)
);
CREATE INDEX ix_case_events_case_id ON case_events (case_id);

CREATE TABLE comparisons (
	id VARCHAR(64) NOT NULL, 
	case_id VARCHAR(64) NOT NULL, 
	mortgage_id VARCHAR(64) NOT NULL, 
	offer_ids_json JSON NOT NULL, 
	horizon_months INTEGER NOT NULL, 
	calculation_version VARCHAR(64) NOT NULL, 
	schedule_refs_json JSON NOT NULL, 
	cash_to_close_json JSON NOT NULL, 
	economic_cost_json JSON NOT NULL, 
	result_json JSON NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id)
);
CREATE INDEX ix_comparisons_case_id ON comparisons (case_id);

CREATE TABLE lender_requests (
	id VARCHAR(64) NOT NULL, 
	case_id VARCHAR(64) NOT NULL, 
	lender_id VARCHAR(64) NOT NULL, 
	target_offer_id VARCHAR(64), 
	competing_offer_id VARCHAR(64), 
	message_json JSON NOT NULL, 
	approved_message_hash VARCHAR(128), 
	disclosed_documents_json JSON NOT NULL, 
	external_request_ref VARCHAR(128), 
	action_id VARCHAR(64), 
	status VARCHAR(32) NOT NULL, 
	response_json JSON NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id)
);
CREATE INDEX ix_lender_requests_case_id ON lender_requests (case_id);

CREATE TABLE loan_offers (
	id VARCHAR(64) NOT NULL, 
	case_id VARCHAR(64) NOT NULL, 
	lender_id VARCHAR(64) NOT NULL, 
	document_id VARCHAR(64), 
	offer_family_id VARCHAR(64) NOT NULL, 
	version INTEGER NOT NULL, 
	currency VARCHAR(3) NOT NULL, 
	principal_minor INTEGER, 
	term_months INTEGER, 
	note_rate_decimal VARCHAR(16), 
	apr_disclosed VARCHAR(16), 
	cost_items_json JSON NOT NULL, 
	credits_minor INTEGER NOT NULL, 
	expires_at TIMESTAMP WITHOUT TIME ZONE, 
	status VARCHAR(32) NOT NULL, 
	normalized_json JSON NOT NULL, 
	provider_reference VARCHAR(128), 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id)
);
CREATE INDEX ix_loan_offers_case_id ON loan_offers (case_id);
CREATE INDEX ix_loan_offers_lender_id ON loan_offers (lender_id);
CREATE INDEX ix_loan_offers_offer_family_id ON loan_offers (offer_family_id);

CREATE TABLE messages (
	id VARCHAR(64) NOT NULL, 
	case_id VARCHAR(64) NOT NULL, 
	role VARCHAR(16) NOT NULL, 
	content TEXT NOT NULL, 
	data_json JSON NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id)
);
CREATE INDEX ix_messages_case_id ON messages (case_id);

CREATE TABLE refinance_applications (
	id VARCHAR(64) NOT NULL, 
	case_id VARCHAR(64) NOT NULL, 
	offer_id VARCHAR(64) NOT NULL, 
	customer_id VARCHAR(64) NOT NULL, 
	lender_id VARCHAR(64) NOT NULL, 
	document_manifest_json JSON NOT NULL, 
	packet_json JSON NOT NULL, 
	external_application_ref VARCHAR(128), 
	client_request_ref VARCHAR(128), 
	conditions_json JSON NOT NULL, 
	final_terms_json JSON, 
	closing_evidence_json JSON, 
	status VARCHAR(32) NOT NULL, 
	action_id VARCHAR(64), 
	revision INTEGER NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES cases (id)
);
CREATE INDEX ix_refinance_applications_case_id ON refinance_applications (case_id);

CREATE TABLE approval_challenges (
	id VARCHAR(64) NOT NULL, 
	action_id VARCHAR(64) NOT NULL, 
	expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	consumed_at TIMESTAMP WITHOUT TIME ZONE, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(action_id) REFERENCES actions (id)
);
CREATE INDEX ix_approval_challenges_action_id ON approval_challenges (action_id);

CREATE TABLE approvals (
	id VARCHAR(64) NOT NULL, 
	action_id VARCHAR(64) NOT NULL, 
	approver_customer_id VARCHAR(64) NOT NULL, 
	action_hash VARCHAR(128) NOT NULL, 
	scope_json JSON NOT NULL, 
	expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	revoked_at TIMESTAMP WITHOUT TIME ZONE, 
	revocation_reason VARCHAR(256), 
	consumed_at TIMESTAMP WITHOUT TIME ZONE, 
	consumed_by_job_id VARCHAR(64), 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(action_id) REFERENCES actions (id)
);
CREATE INDEX ix_approvals_action_id ON approvals (action_id);

CREATE TABLE term_reviews (
	id VARCHAR(64) NOT NULL, 
	application_id VARCHAR(64) NOT NULL, 
	earlier_offer_id VARCHAR(64) NOT NULL, 
	final_terms_id VARCHAR(64) NOT NULL, 
	differences_json JSON NOT NULL, 
	requires_reapproval BOOLEAN NOT NULL, 
	reviewed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(application_id) REFERENCES refinance_applications (id)
);
CREATE INDEX ix_term_reviews_application_id ON term_reviews (application_id);

COMMIT;
