-- Generated by scripts/export_schema.py from backend/app/persistence/models.py. Do not edit by hand.
BEGIN;

CREATE TABLE a2a_task_map (
	external_task_id VARCHAR(120) NOT NULL, 
	case_id VARCHAR(64) NOT NULL, 
	action_id VARCHAR(64) NOT NULL, 
	protocol_version VARCHAR(16) NOT NULL, 
	created_at VARCHAR(40) NOT NULL, 
	PRIMARY KEY (external_task_id)
);
CREATE INDEX ix_a2a_task_map_case_id ON a2a_task_map (case_id);

CREATE TABLE customers (
	id VARCHAR(64) NOT NULL, 
	tenant_id VARCHAR(64) NOT NULL, 
	full_name VARCHAR(200) NOT NULL, 
	email_masked VARCHAR(200) NOT NULL, 
	payout_destination_json JSON NOT NULL, 
	created_at VARCHAR(40) NOT NULL, 
	PRIMARY KEY (id)
);

CREATE TABLE inbox_events (
	id VARCHAR(64) NOT NULL, 
	provider VARCHAR(64) NOT NULL, 
	provider_event_id VARCHAR(120) NOT NULL, 
	event_type VARCHAR(64) NOT NULL, 
	payload_json JSON NOT NULL, 
	outcome VARCHAR(40) NOT NULL, 
	duplicate_deliveries INTEGER NOT NULL, 
	received_at VARCHAR(40) NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_inbox_provider_event UNIQUE (provider, provider_event_id)
);

CREATE TABLE jobs (
	id VARCHAR(64) NOT NULL, 
	job_type VARCHAR(64) NOT NULL, 
	payload_json JSON NOT NULL, 
	run_at VARCHAR(40) NOT NULL, 
	lease_until VARCHAR(40), 
	locked_by VARCHAR(64), 
	attempts INTEGER NOT NULL, 
	max_attempts INTEGER NOT NULL, 
	status VARCHAR(16) NOT NULL, 
	last_error TEXT, 
	dedupe_key VARCHAR(160), 
	created_at VARCHAR(40) NOT NULL, 
	finished_at VARCHAR(40), 
	PRIMARY KEY (id), 
	UNIQUE (dedupe_key)
);
CREATE INDEX ix_jobs_pending ON jobs (status, run_at);

CREATE TABLE mock_insurer_claims (
	claim_ref VARCHAR(120) NOT NULL, 
	request_ref VARCHAR(120) NOT NULL, 
	packet_json JSON NOT NULL, 
	scenario VARCHAR(40) NOT NULL, 
	status VARCHAR(32) NOT NULL, 
	submissions_json JSON NOT NULL, 
	decision_json JSON, 
	open_request_json JSON, 
	event_sequence INTEGER NOT NULL, 
	created_at VARCHAR(40) NOT NULL, 
	updated_at VARCHAR(40) NOT NULL, 
	PRIMARY KEY (claim_ref), 
	UNIQUE (request_ref)
);

CREATE TABLE mock_request_refs (
	request_ref VARCHAR(120) NOT NULL, 
	claim_ref VARCHAR(120) NOT NULL, 
	operation VARCHAR(32) NOT NULL, 
	result_json JSON NOT NULL, 
	created_at VARCHAR(40) NOT NULL, 
	PRIMARY KEY (request_ref)
);

CREATE TABLE outbox_messages (
	id VARCHAR(64) NOT NULL, 
	case_id VARCHAR(64), 
	event_type VARCHAR(64) NOT NULL, 
	payload_json JSON NOT NULL, 
	status VARCHAR(16) NOT NULL, 
	attempts INTEGER NOT NULL, 
	signature VARCHAR(120), 
	created_at VARCHAR(40) NOT NULL, 
	delivered_at VARCHAR(40), 
	PRIMARY KEY (id)
);
CREATE INDEX ix_outbox_messages_case_id ON outbox_messages (case_id);

CREATE TABLE principals (
	id VARCHAR(64) NOT NULL, 
	token_hash VARCHAR(80) NOT NULL, 
	role VARCHAR(32) NOT NULL, 
	customer_id VARCHAR(64), 
	display_name VARCHAR(200) NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (token_hash)
);

CREATE TABLE provider_request_log (
	id VARCHAR(64) NOT NULL, 
	case_id VARCHAR(64), 
	adapter VARCHAR(32) NOT NULL, 
	operation VARCHAR(32) NOT NULL, 
	request_ref VARCHAR(120), 
	outcome VARCHAR(24) NOT NULL, 
	environment VARCHAR(16) NOT NULL, 
	detail_json JSON NOT NULL, 
	created_at VARCHAR(40) NOT NULL, 
	PRIMARY KEY (id)
);
CREATE INDEX ix_provider_request_log_case_id ON provider_request_log (case_id);

CREATE TABLE tool_runs (
	id VARCHAR(64) NOT NULL, 
	case_id VARCHAR(64), 
	turn_id VARCHAR(64), 
	tool_name VARCHAR(64) NOT NULL, 
	input_ref VARCHAR(80) NOT NULL, 
	output_ref VARCHAR(80) NOT NULL, 
	input_summary_json JSON NOT NULL, 
	source_timestamp VARCHAR(40) NOT NULL, 
	latency_ms INTEGER NOT NULL, 
	model_version VARCHAR(64) NOT NULL, 
	prompt_version VARCHAR(32) NOT NULL, 
	outcome VARCHAR(16) NOT NULL, 
	created_at VARCHAR(40) NOT NULL, 
	PRIMARY KEY (id)
);
CREATE INDEX ix_tool_runs_case_id ON tool_runs (case_id);

CREATE TABLE documents (
	id VARCHAR(64) NOT NULL, 
	owner_customer_id VARCHAR(64) NOT NULL, 
	doc_type VARCHAR(64) NOT NULL, 
	object_key VARCHAR(200) NOT NULL, 
	content_hash VARCHAR(80) NOT NULL, 
	source VARCHAR(64) NOT NULL, 
	captured_at VARCHAR(40) NOT NULL, 
	extraction_version VARCHAR(32) NOT NULL, 
	content_json JSON NOT NULL, 
	version INTEGER NOT NULL, 
	created_at VARCHAR(40) NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(owner_customer_id) REFERENCES customers (id)
);

CREATE TABLE policies (
	id VARCHAR(64) NOT NULL, 
	customer_id VARCHAR(64) NOT NULL, 
	insurer_name VARCHAR(200) NOT NULL, 
	fixture_json JSON NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(customer_id) REFERENCES customers (id)
);

CREATE TABLE claim_cases (
	id VARCHAR(64) NOT NULL, 
	tenant_id VARCHAR(64) NOT NULL, 
	customer_id VARCHAR(64) NOT NULL, 
	policy_id VARCHAR(64) NOT NULL, 
	policy_version VARCHAR(32), 
	workflow_type VARCHAR(64) NOT NULL, 
	loss_type VARCHAR(64) NOT NULL, 
	loss_at VARCHAR(40) NOT NULL, 
	status VARCHAR(40) NOT NULL, 
	version INTEGER NOT NULL, 
	external_claim_ref VARCHAR(120), 
	mock_scenario VARCHAR(40), 
	evaluation_json JSON, 
	followups_used INTEGER NOT NULL, 
	completion_evidence_ref VARCHAR(120), 
	created_at VARCHAR(40) NOT NULL, 
	updated_at VARCHAR(40) NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(customer_id) REFERENCES customers (id), 
	FOREIGN KEY(policy_id) REFERENCES policies (id)
);
CREATE INDEX ix_claim_cases_customer_id ON claim_cases (customer_id);

CREATE TABLE agent_turns (
	id VARCHAR(64) NOT NULL, 
	case_id VARCHAR(64) NOT NULL, 
	actor VARCHAR(64) NOT NULL, 
	customer_message TEXT NOT NULL, 
	response_json JSON NOT NULL, 
	tool_calls INTEGER NOT NULL, 
	planner VARCHAR(32) NOT NULL, 
	created_at VARCHAR(40) NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES claim_cases (id)
);
CREATE INDEX ix_agent_turns_case_id ON agent_turns (case_id);

CREATE TABLE case_documents (
	case_id VARCHAR(64) NOT NULL, 
	document_id VARCHAR(64) NOT NULL, 
	attached_at VARCHAR(40) NOT NULL, 
	PRIMARY KEY (case_id, document_id), 
	FOREIGN KEY(case_id) REFERENCES claim_cases (id), 
	FOREIGN KEY(document_id) REFERENCES documents (id)
);

CREATE TABLE case_events (
	id VARCHAR(64) NOT NULL, 
	case_id VARCHAR(64) NOT NULL, 
	sequence INTEGER NOT NULL, 
	event_type VARCHAR(64) NOT NULL, 
	source_event_id VARCHAR(120), 
	actor VARCHAR(64) NOT NULL, 
	previous_state VARCHAR(40), 
	next_state VARCHAR(40), 
	expected_case_version INTEGER, 
	data_json JSON NOT NULL, 
	occurred_at VARCHAR(40) NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_case_event_sequence UNIQUE (case_id, sequence), 
	FOREIGN KEY(case_id) REFERENCES claim_cases (id)
);
CREATE INDEX ix_case_events_case_id ON case_events (case_id);

CREATE TABLE case_questions (
	id VARCHAR(64) NOT NULL, 
	case_id VARCHAR(64) NOT NULL, 
	field VARCHAR(80) NOT NULL, 
	question TEXT NOT NULL, 
	fact_id VARCHAR(64), 
	expense_id VARCHAR(64), 
	status VARCHAR(16) NOT NULL, 
	answer_json JSON, 
	asked_by VARCHAR(64) NOT NULL, 
	created_at VARCHAR(40) NOT NULL, 
	answered_at VARCHAR(40), 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES claim_cases (id)
);
CREATE INDEX ix_case_questions_case_id ON case_questions (case_id);

CREATE TABLE claim_decisions (
	id VARCHAR(64) NOT NULL, 
	case_id VARCHAR(64) NOT NULL, 
	decision_version INTEGER NOT NULL, 
	outcome VARCHAR(24) NOT NULL, 
	accepted_minor INTEGER NOT NULL, 
	rejected_minor INTEGER NOT NULL, 
	currency VARCHAR(3) NOT NULL, 
	reason_items_json JSON NOT NULL, 
	evidence_id VARCHAR(64), 
	explanation_json JSON, 
	appeal_status VARCHAR(24) NOT NULL, 
	provider_decision_ref VARCHAR(120) NOT NULL, 
	decided_at VARCHAR(40) NOT NULL, 
	created_at VARCHAR(40) NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_decision_version UNIQUE (case_id, decision_version), 
	FOREIGN KEY(case_id) REFERENCES claim_cases (id)
);
CREATE INDEX ix_claim_decisions_case_id ON claim_decisions (case_id);

CREATE TABLE claim_facts (
	id VARCHAR(64) NOT NULL, 
	case_id VARCHAR(64) NOT NULL, 
	fact_type VARCHAR(64) NOT NULL, 
	value_json JSON NOT NULL, 
	evidence_id VARCHAR(64), 
	source_locator VARCHAR(200) NOT NULL, 
	confidence VARCHAR(16) NOT NULL, 
	uncertainty_flags_json JSON NOT NULL, 
	confirmation_status VARCHAR(32) NOT NULL, 
	confirmed_by VARCHAR(64), 
	confirmed_at VARCHAR(40), 
	superseded BOOLEAN NOT NULL, 
	created_at VARCHAR(40) NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES claim_cases (id)
);
CREATE INDEX ix_claim_facts_case_id ON claim_facts (case_id);

CREATE TABLE claim_payments (
	id VARCHAR(64) NOT NULL, 
	case_id VARCHAR(64), 
	decision_id VARCHAR(64), 
	provider_payment_ref VARCHAR(120) NOT NULL, 
	claim_reference VARCHAR(120) NOT NULL, 
	payee_id VARCHAR(64) NOT NULL, 
	amount_minor INTEGER NOT NULL, 
	currency VARCHAR(3) NOT NULL, 
	payment_status VARCHAR(16) NOT NULL, 
	posted_at VARCHAR(40) NOT NULL, 
	reconciliation_status VARCHAR(32) NOT NULL, 
	reconciliation_json JSON, 
	environment VARCHAR(16) NOT NULL, 
	created_at VARCHAR(40) NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES claim_cases (id), 
	UNIQUE (provider_payment_ref)
);
CREATE INDEX ix_claim_payments_case_id ON claim_payments (case_id);

CREATE TABLE claimed_expenses (
	id VARCHAR(64) NOT NULL, 
	case_id VARCHAR(64) NOT NULL, 
	receipt_id VARCHAR(64) NOT NULL, 
	receipt_hash VARCHAR(80) NOT NULL, 
	merchant VARCHAR(200) NOT NULL, 
	purchased_at VARCHAR(40), 
	amount_minor INTEGER NOT NULL, 
	currency VARCHAR(3) NOT NULL, 
	category VARCHAR(40) NOT NULL, 
	description TEXT NOT NULL, 
	eligibility_status VARCHAR(24) NOT NULL, 
	rule_id VARCHAR(64), 
	exclusion_reason TEXT, 
	duplicate_of VARCHAR(64), 
	source_locator VARCHAR(200) NOT NULL, 
	receipt_flags_json JSON NOT NULL, 
	confirmations_json JSON NOT NULL, 
	created_order INTEGER NOT NULL, 
	created_at VARCHAR(40) NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES claim_cases (id)
);
CREATE INDEX ix_claimed_expenses_case_id ON claimed_expenses (case_id);

CREATE TABLE insurer_requests (
	id VARCHAR(64) NOT NULL, 
	case_id VARCHAR(64) NOT NULL, 
	provider_request_id VARCHAR(120) NOT NULL, 
	requirement_json JSON NOT NULL, 
	due_at VARCHAR(40), 
	deadline_source VARCHAR(120) NOT NULL, 
	status VARCHAR(16) NOT NULL, 
	satisfied_by_submission_id VARCHAR(64), 
	created_at VARCHAR(40) NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_insurer_request UNIQUE (case_id, provider_request_id), 
	FOREIGN KEY(case_id) REFERENCES claim_cases (id)
);
CREATE INDEX ix_insurer_requests_case_id ON insurer_requests (case_id);

CREATE TABLE packets (
	id VARCHAR(64) NOT NULL, 
	case_id VARCHAR(64) NOT NULL, 
	packet_type VARCHAR(24) NOT NULL, 
	content_hash VARCHAR(80) NOT NULL, 
	content_json JSON NOT NULL, 
	case_version INTEGER NOT NULL, 
	created_at VARCHAR(40) NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES claim_cases (id)
);
CREATE INDEX ix_packets_case_id ON packets (case_id);

CREATE TABLE actions (
	id VARCHAR(64) NOT NULL, 
	case_id VARCHAR(64) NOT NULL, 
	action_type VARCHAR(32) NOT NULL, 
	packet_id VARCHAR(64) NOT NULL, 
	payload_hash VARCHAR(80) NOT NULL, 
	idempotency_key VARCHAR(120) NOT NULL, 
	status VARCHAR(24) NOT NULL, 
	approval_id VARCHAR(64), 
	provider_ref VARCHAR(120), 
	expected_case_version INTEGER NOT NULL, 
	review_summary_json JSON NOT NULL, 
	result_json JSON, 
	attempts INTEGER NOT NULL, 
	created_at VARCHAR(40) NOT NULL, 
	updated_at VARCHAR(40) NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(case_id) REFERENCES claim_cases (id), 
	FOREIGN KEY(packet_id) REFERENCES packets (id), 
	UNIQUE (idempotency_key)
);
CREATE INDEX ix_actions_case_id ON actions (case_id);

CREATE TABLE claim_submissions (
	id VARCHAR(64) NOT NULL, 
	case_id VARCHAR(64) NOT NULL, 
	sequence INTEGER NOT NULL, 
	submission_kind VARCHAR(24) NOT NULL, 
	packet_id VARCHAR(64) NOT NULL, 
	packet_hash VARCHAR(80) NOT NULL, 
	approval_id VARCHAR(64) NOT NULL, 
	action_id VARCHAR(64) NOT NULL, 
	external_claim_ref VARCHAR(120), 
	external_submission_ref VARCHAR(120), 
	submitted_at VARCHAR(40) NOT NULL, 
	status VARCHAR(24) NOT NULL, 
	environment VARCHAR(16) NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_submission_sequence UNIQUE (case_id, sequence), 
	FOREIGN KEY(case_id) REFERENCES claim_cases (id), 
	FOREIGN KEY(packet_id) REFERENCES packets (id)
);
CREATE INDEX ix_claim_submissions_case_id ON claim_submissions (case_id);

CREATE TABLE approval_challenges (
	id VARCHAR(64) NOT NULL, 
	action_id VARCHAR(64) NOT NULL, 
	expires_at VARCHAR(40) NOT NULL, 
	status VARCHAR(16) NOT NULL, 
	created_at VARCHAR(40) NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(action_id) REFERENCES actions (id)
);

CREATE TABLE approvals (
	id VARCHAR(64) NOT NULL, 
	action_id VARCHAR(64) NOT NULL, 
	approver_id VARCHAR(64) NOT NULL, 
	action_hash VARCHAR(80) NOT NULL, 
	scope VARCHAR(64) NOT NULL, 
	expires_at VARCHAR(40) NOT NULL, 
	revoked_at VARCHAR(40), 
	consumed_at VARCHAR(40), 
	consumed_by VARCHAR(64), 
	created_at VARCHAR(40) NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(action_id) REFERENCES actions (id)
);

COMMIT;
