import {test,expect} from '@playwright/test'
test('two jobs to verified mock refund, with evidence and responsive views',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/')
 await expect(page.getByRole('heading',{name:'Your return, in order.'})).toBeVisible()
 await page.getByRole('button',{name:'Confirm your situation',exact:true}).click()
 await page.getByRole('button',{name:'Use sample answers'}).click()
 await page.getByRole('button',{name:'Confirm supported profile'}).click()
 await page.getByRole('button',{name:'Import sample documents'}).click()
 await expect(page.getByRole('button',{name:/Northstar Studio W-2/})).toBeVisible()
 await page.getByLabel('I have reviewed all records.').check()
 await page.getByRole('button',{name:'Reconcile documents',exact:true}).click()
 await page.getByRole('button',{name:'Prepare my draft',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Every number, accounted for.'})).toBeVisible()
 await expect(page.getByText('$862',{exact:true}).first()).toBeVisible()
 await page.getByRole('button',{name:'Evidence for line 1a',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Line 1a · Wages from W-2s'})).toBeVisible()
 await page.getByRole('button',{name:'Close dialog'}).click()
 await page.getByRole('button',{name:'Overview',exact:true}).click()
 await page.screenshot({path:'../docs/screenshot-desktop.png',fullPage:true})
 await page.getByRole('button',{name:'Your return',exact:true}).click()
 await page.getByRole('button',{name:'Review & approve'}).click()
 await expect(page.getByRole('button',{name:'Approve mock submission'})).toBeDisabled()
 await page.getByLabel('I reviewed the worksheet, source records').check()
 await page.getByRole('button',{name:'Approve mock submission'}).click()
 await expect(page.getByText('received',{exact:true})).toBeVisible({timeout:15000})
 await page.getByRole('button',{name:'Advance one day'}).click()
 await expect(page.getByText('refund pending',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Advance one day'}).click()
 await expect(page.getByText('refund pending',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Advance one day'}).click()
 await expect(page.getByText('refund verified',{exact:true})).toBeVisible()
 await page.reload()
 await page.getByRole('button',{name:'Filing & refund',exact:true}).click()
 await expect(page.getByText('refund verified',{exact:true})).toBeVisible()
 await page.setViewportSize({width:390,height:844})
 await page.getByRole('button',{name:'Overview',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Your return, in order.'})).toBeVisible()
 await page.screenshot({path:'../docs/screenshot-mobile.png',fullPage:true})
 const width=await page.evaluate(()=>({body:document.body.scrollWidth,viewport:innerWidth}))
 expect(width.body).toBeLessThanOrEqual(width.viewport)
 expect(errors).toEqual([])
})
