import React, { useEffect, useRef, useState } from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight, ArrowRight, ArrowLeft, Check, CheckCheck, ChevronDown, ChevronRight, CircleHelp, Clock3, Download, FileCheck2, FileText, Globe2, History, Landmark, LayoutDashboard, Loader2, LockKeyhole, MoreHorizontal, Plus, RefreshCw, Send, Settings2, ShieldCheck, Sparkles, Users, X, AlertCircle, CheckCircle2, FlaskConical, Zap, CircleDollarSign, Activity, Command, ExternalLink} from 'lucide-react';
import {api,money,date,label} from './api';
import type {Action,Bootstrap,Case,CaseSummary,Overview,Quote,Recipient} from './types';
import './style.css';

type Page='send'|'activity'|'recipients'|'operations';
const names:Record<string,string>={swift:'SwiftSend',bridge:'BridgeWay',lotus:'Lotus Remit'};
const statusCopy:Record<string,string>={initiating:'Preparing your transfer',funding_pending:'Waiting for source funding',processing:'Your transfer is processing',payout_pending:'On its way to the recipient bank',outcome_unknown:'Checking with your provider',information_required:'A little more information is needed',delayed:'Your transfer is taking longer',manual_review:'Your transfer needs a closer look',reconciled:'It’s arrived. And accounted for.',cancelled:'Your transfer was cancelled',rejected:'The provider declined this transfer',cancellation_requested:'Cancellation requested'};
function Logo({small=false}:{small?:boolean}){return <div className={'brand '+(small?'small':'')}><span className="brand-mark"><Send size={small?18:24} strokeWidth={1.7}/></span>{!small&&<span>passage<span className="brand-period">.</span></span>}</div>}
function ProviderIcon({id}:{id:string}){return <span className={'provider-icon '+id}>{id==='swift'?<Zap size={23} fill="currentColor"/>:id==='bridge'?<Command size={24}/>:<Globe2 size={24}/>}</span>}
function Status({value}:{value:string}){return <span className={'status '+(['reconciled','verified','matched','satisfied','done','completed','applied'].includes(value)?'good':['information_required','outcome_unknown','delayed','manual_review','failed','deferred','rejected'].includes(value)?'warn':'')}><span/>{label(value)}</span>}
function App(){
 const [page,setPage]=useState<Page>('send'),[boot,setBoot]=useState<Bootstrap|null>(null),[current,setCurrent]=useState<Case|null>(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[toast,setToast]=useState('');
 const [amount,setAmount]=useState('500'),[mode,setMode]=useState('total_sender_cost'),[recipientId,setRecipientId]=useState('beneficiary_demo_1'),[hours,setHours]=useState('24'),[purpose,setPurpose]=useState('family_support'),[confirmed,setConfirmed]=useState(false),[editing,setEditing]=useState(false);
 const [action,setAction]=useState<Action|null>(null),[approvedCheck,setApprovedCheck]=useState(false),[help,setHelp]=useState(false),[chat,setChat]=useState(''),[answer,setAnswer]=useState(''),[operatorToken,setOperatorToken]=useState(''),[overview,setOverview]=useState<Overview|null>(null),[operatorTab,setOperatorTab]=useState('cases');
 const dialog=useRef<HTMLDialogElement>(null),helpDialog=useRef<HTMLDialogElement>(null),toastTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
 const active=!!current?.transfer&&current.transfer.status!=='prepared';
 const recipients=boot?.recipients??[];
 const recipient=recipients.find(r=>r.id===recipientId)??recipients[0];
 const notify=(text:string)=>{setToast(text);clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),4500)};
 async function refresh(id?:string){const b=await api<Bootstrap>('/v1/bootstrap');setBoot(b);if(id){const c=await api<Case>(`/v1/remittance-cases/${id}`);setCurrent(c);localStorage.setItem('passage-case',id);return c}}
 async function run(name:string,fn:()=>Promise<void>){setBusy(name);setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 async function createComparison(b:Bootstrap,sourceAmount='500',sourceMode='total_sender_cost',beneficiary='beneficiary_demo_1',deadlineHours='24',transferPurpose='family_support'){
   const minor=Math.round(Number(sourceAmount)*100);
   if(!Number.isFinite(minor)||minor<=0) throw new Error('Enter an amount greater than zero.');
   const created=await api<CaseSummary>('/v1/remittance-cases',{customer_id:'cus_demo_8',beneficiary_id:beneficiary,budget_mode:sourceMode,source_budget_minor:sourceMode==='total_sender_cost'?minor:null,target_required_minor:sourceMode==='recipient_target'?minor:null,deadline_at:new Date(new Date(b.clock).getTime()+Number(deadlineHours)*3600000).toISOString(),purpose:transferPurpose,recipient_confirmed:false});
   await api(`/v1/remittance-cases/${created.id}/quotes`,{});await refresh(created.id);setConfirmed(false);setEditing(false);setAnswer('');
 }
 useEffect(()=>{void run('loading',async()=>{let b:Bootstrap;try{b=await api<Bootstrap>('/v1/bootstrap')}catch{await api('/v1/demo/session',{});b=await api<Bootstrap>('/v1/bootstrap')}setBoot(b);const saved=localStorage.getItem('passage-case');const previous=b.cases.find(c=>c.id===saved)??b.cases[0];if(previous){const c=await refresh(previous.id);if(c){setRecipientId(c.beneficiary_id);setMode(c.budget_mode);setAmount(String((c.source_budget_minor??c.target_required_minor??50000)/100));setPurpose(c.purpose)}}else await createComparison(b)})},[]);
 useEffect(()=>{if(!current||action)return;const timer=setInterval(()=>{void api<Case>(`/v1/remittance-cases/${current.id}`).then(setCurrent).catch(()=>{})},2500);return()=>clearInterval(timer)},[current?.id,action]);
 useEffect(()=>{if(action){setApprovedCheck(false);dialog.current?.showModal()}else dialog.current?.close()},[action]);
 useEffect(()=>{if(help)helpDialog.current?.showModal();else helpDialog.current?.close()},[help]);
 async function selectCase(id:string){await run('loading',async()=>{const c=await refresh(id);if(c){setRecipientId(c.beneficiary_id);setMode(c.budget_mode);setAmount(String((c.source_budget_minor??c.target_required_minor??50000)/100));setPurpose(c.purpose)}setPage('send');setEditing(false);setConfirmed(false);setAnswer('')})}
 async function loadOps(){await run('operations',async()=>{let token=operatorToken;if(!token){const s=await api<{access_token:string}>('/v1/demo/session',{persona:'operator'});token=s.access_token;setOperatorToken(token)}setOverview(await api<Overview>('/v1/operator/overview',undefined,token));setPage('operations')})}
 async function navigate(next:Page){if(next==='operations'){await loadOps();return}setPage(next);if(next==='activity')await run('activity',async()=>{await refresh()})}
 async function review(q:Quote){if(!current)return;await run(q.id,async()=>{const a=await api<Action>(`/v1/remittance-cases/${current.id}/transfer-drafts`,{expected_case_version:current.version,quote_id:q.id,recipient_version:current.recipient.version,recipient_confirmed:true},undefined,crypto.randomUUID());await refresh(current.id);setAction(a)})}
 async function approveAction(){if(!action||!current)return;await run('approve',async()=>{await api(`/v1/actions/${action.id}/approve`,{expected_case_version:action.expected_case_version,action_payload_hash:action.payload_hash,approval_challenge_id:action.challenge_id});setAction(null);await refresh(current.id);notify('Approval recorded. Your provider request is being processed.')})}
 async function followup(kind:'documents'|'cancel'){if(!current?.transfer)return;await run(kind,async()=>{const body=kind==='documents'?{expected_case_version:current.version,requirement_id:current.requirements.find(r=>r.status==='open')?.id,document_ids:['doc_purpose_demo']}:{expected_case_version:current.version};const a=await api<Action>(`/v1/remittance-transfers/${current.transfer!.id}/${kind==='documents'?'document-packets':'cancellation-drafts'}`,body,undefined,crypto.randomUUID());await refresh(current.id);setAction(a)})}
 async function advance(minutes:number){await run('clock',async()=>{await api('/v1/demo/advance',{minutes});await refresh(current?.id);if(page==='operations'&&operatorToken)setOverview(await api<Overview>('/v1/operator/overview',undefined,operatorToken));notify(`Demo clock advanced by ${minutes<60?minutes+' minutes':minutes/60+' hours'}.`)})}
 async function ask(message:string){if(!current)return;await run('chat',async()=>{const r=await api<{message:string}>('/v1/concierge/chat',{case_id:current.id,message});setAnswer(r.message);setChat('')})}
 const nav=[{id:'send' as Page,name:'Send money',icon:Send},{id:'activity' as Page,name:'Transfer activity',icon:History},{id:'recipients' as Page,name:'Your recipients',icon:Users}];
 return <div className="app-shell">
  <aside className="sidebar"><Logo/><div className="workspace-label">YOUR WORKSPACE</div><nav aria-label="Main navigation">{nav.map(n=><button className={page===n.id?'selected':''} key={n.id} onClick={()=>void navigate(n.id)}><n.icon size={19}/>{n.name}{page===n.id&&<span className="nav-active"/>}</button>)}</nav>
   <div className="side-note"><Globe2 size={26}/><h3>A world closer.</h3><p>One clear view from your account to theirs.</p><div className="side-corridor"><span>US</span><span className="dashed-line"/><ArrowRight size={15}/><span>IN</span></div></div>
   <div className="sidebar-bottom"><button onClick={()=>void navigate('operations')} className={page==='operations'?'selected':''}><Settings2 size={19}/>Operations console<ArrowUpRight size={16}/></button><button onClick={()=>setHelp(true)}><CircleHelp size={19}/>About this demo</button><div className="profile"><div className="avatar">AM</div><div><strong>Alex Morgan</strong><span>Personal account · US</span></div><ShieldCheck size={17}/></div></div>
  </aside>
  <div className="workspace"><header className="topbar"><div className="mobile-brand"><Logo small/></div><span className="breadcrumb">Personal account <ChevronRight size={14}/> <strong>{page==='send'?'Send money':page==='activity'?'Transfer activity':page==='recipients'?'Your recipients':'Operations'}</strong></span><div className="topbar-right"><span className="demo-pill"><FlaskConical size={14}/>Simulation mode</span><button className="icon-button" aria-label="About this demo" onClick={()=>setHelp(true)}><CircleHelp size={20}/></button></div></header>
  <main>
  {error&&<div className="error-banner" role="alert"><AlertCircle size={18}/><span>{error}</span><button aria-label="Dismiss error" onClick={()=>setError('')}><X size={17}/></button></div>}
  {busy==='loading'&&!current?<div className="loading-state"><Loader2 className="spin" size={30}/><h2>Getting your workspace ready</h2><p>Loading verified recipients and provider quotes.</p></div>:<>
  {page==='send'&&<>
   <div className="page-heading"><div><div className="eyebrow">ACROSS BORDERS. ALL ACCOUNTED FOR.</div><h1>{active?'Your transfer, every step.':'Send money to India'}</h1><p>{active?'Follow the original transfer from approval to verified arrival.':'Compare what arrives. Choose what works for you.'}</p></div><button className="text-button" onClick={()=>{setEditing(true);setCurrent(null);setConfirmed(false);setAmount('500');setMode('total_sender_cost')}}><Plus size={17}/>New transfer</button></div>
   <div className="journey" aria-label="Transfer steps">{['Transfer details','Compare & choose','Review & approve','Track delivery'].map((step,i)=><React.Fragment key={step}><div className={(active?i<3:i===0&&current)?'step complete':(active?i===3:i===(action?2:1))?'step current':'step'}><span>{(active?i<3:i===0&&current)?<Check size={13}/>:`0${i+1}`}</span>{step}</div>{i<3&&<div className="step-line"/>}</React.Fragment>)}</div>
   {!active?<div className="send-layout">
    <section className="transfer-details panel"><div className="panel-title"><h2>Your transfer</h2><span className="mini-label">USD <ArrowRight size={12}/> INR</span></div>
      <div className="segmented" aria-label="Amount mode"><button className={mode==='total_sender_cost'?'active':''} onClick={()=>{setMode('total_sender_cost');setAmount('500');setEditing(true)}}>You send</button><button className={mode==='recipient_target'?'active':''} onClick={()=>{setMode('recipient_target');setAmount('41000');setEditing(true)}}>They receive</button></div>
      <label className="field-label" htmlFor="amount">{mode==='total_sender_cost'?'Your total budget, including fees':'Their target amount, after deductions'}</label><div className="amount-input"><span>{mode==='total_sender_cost'?'$':'₹'}</span><input id="amount" type="number" min={mode==='total_sender_cost'?'10':'100'} max={mode==='total_sender_cost'?'10000':'830000'} step="0.01" value={amount} onChange={e=>{setAmount(e.target.value);setEditing(true)}}/><div className="currency"><span>{mode==='total_sender_cost'?'🇺🇸':'🇮🇳'}</span>{mode==='total_sender_cost'?'USD':'INR'}</div></div>
      <div className="currency-route"><span className="route-line"/><ArrowRight size={15}/><span>To an Indian bank account</span><span>🇮🇳</span></div>
      <label className="field-label" htmlFor="recipient">Sending to</label><div className="select-wrap"><select id="recipient" value={recipientId} onChange={e=>{setRecipientId(e.target.value);setEditing(true);setConfirmed(false)}}>{recipients.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><ChevronDown size={15}/></div>
      {recipient&&<div className="recipient-card"><div className="avatar recipient-avatar">{recipient.name.split(' ').map(n=>n[0]).join('')}</div><div><strong>{recipient.bank} <span>{recipient.account_mask}</span></strong><span>{recipient.city}</span></div><ShieldCheck size={19}/></div>}
      <div className="field-row"><div><label className="field-label" htmlFor="deadline">Arrive within</label><div className="select-wrap"><select id="deadline" value={hours} onChange={e=>{setHours(e.target.value);setEditing(true)}}><option value="2">2 hours</option><option value="6">6 hours</option><option value="12">12 hours</option><option value="24">24 hours</option><option value="48">48 hours</option><option value="72">3 days</option></select><ChevronDown size={14}/></div></div><div><label className="field-label" htmlFor="purpose">Purpose</label><div className="select-wrap"><select id="purpose" value={purpose} onChange={e=>{setPurpose(e.target.value);setEditing(true)}}><option value="family_support">Family support</option><option value="education">Education</option><option value="medical">Medical</option><option value="savings">Savings</option></select><ChevronDown size={14}/></div></div></div>
      <button className="primary full" disabled={!!busy||!boot} onClick={()=>void run('compare',async()=>{if(boot)await createComparison(boot,amount,mode,recipientId,hours,purpose)})}>{busy==='compare'?<Loader2 className="spin" size={18}/>:<RefreshCw size={17}/>} {current?'Update comparison':'Compare providers'}</button>
      <div className="security-note"><LockKeyhole size={14}/>Your money moves only after you approve.</div>
      <div className="details-divider"/>
      <div className="verified-heading"><ShieldCheck size={18}/><strong>Know exactly where it’s going.</strong></div><p className="small-note">Check your recipient’s name and bank details before choosing a provider.</p>
      <label className="checkbox-label"><input type="checkbox" checked={confirmed} disabled={editing||!current} onChange={e=>setConfirmed(e.target.checked)}/><span>I confirm {current?.recipient.name??recipient?.name} and the verified account ending {current?.recipient.account_mask.slice(-4)??recipient?.account_mask.slice(-4)}.</span></label>
    </section>
    <section className="comparison"><div className="comparison-header"><div><h2>Your options <span className="count-badge">{current?.comparison.quotes.length??0}</span></h2><p>{current?`Total sender ${current.budget_mode==='total_sender_cost'?'budget':'cost'} · ${current.budget_mode==='total_sender_cost'?money(current.source_budget_minor??0):'calculated per provider'}`:'Set your transfer details to see live simulator quotes.'}</p></div><span className="live-label"><Clock3 size={14}/>15-minute quotes</span></div>
    {editing&&current&&<div className="inline-note"><RefreshCw size={16}/>Details changed. Update your comparison to see matching quotes.</div>}
    {current?.comparison.quotes.length? <>
      {!current.comparison.recommended_quote_id&&<div className="inline-note amber"><AlertCircle size={17}/>{current.comparison.explanation}</div>}
      <div className="quote-list">{current.comparison.quotes.map(q=><article className={'quote-card '+(q.recommended?'recommended ':'')+(!q.eligible?'unavailable':'')} key={q.id}>
       {q.recommended&&<div className="recommendation-ribbon"><Sparkles size={13}/>BEST FIT FOR YOUR TRANSFER<span>{current.budget_mode==='recipient_target'?'Lowest total cost':'Most INR within your deadline'}</span></div>}
       <div className="quote-main"><div className="provider"><ProviderIcon id={q.provider_id}/><div><h3>{q.provider_name}</h3><span>{q.provider_id==='swift'?'Express bank transfer':q.provider_id==='bridge'?'Bank-to-bank transfer':'Economy bank transfer'}</span></div></div><div className="receive-amount"><span>They receive</span><strong>{money(q.recipient_minor,'INR')}</strong></div></div>
       <div className="quote-meta"><div><span>Transfer fee</span><strong>{money(q.fee_minor)}</strong></div><div><span>Exchange rate</span><strong>₹{q.effective_rate_decimal} <small>/ $1</small></strong></div><div><span>Estimated arrival</span><strong><Clock3 size={13}/>{q.delivery_window.hours[0]}–{q.delivery_window.hours[1]} hours</strong></div></div>
       <div className="quote-footer"><div>{q.known_deduction_minor>0?<span><CircleDollarSign size={14}/>{money(q.known_deduction_minor,'INR')} payout deduction included</span>:<span><Check size={14}/>No additional known deductions</span>}<small>You pay {money(q.source_total_minor)}{!q.eligible?' · '+(q.expired?'Quote expired':'Outside your deadline'):''}</small></div><button className={q.recommended?'primary small':'secondary small'} disabled={!confirmed||editing||!q.eligible||!!busy} onClick={()=>void review(q)}>{busy===q.id?<Loader2 className="spin" size={16}/>:<>Review quote<ArrowRight size={15}/></>}</button></div>
      </article>)}</div>
      <div className="comparison-footnote"><ShieldCheck size={15}/><span>Fees and known deductions are included. All rates are fixtures and arrival times are estimates.</span></div>
    </>:<div className="empty-state"><Globe2 size={40}/><h3>Find the right way across</h3><p>Enter an amount and a deadline to compare three simulated providers.</p></div>}
    <ConciergeBox answer={answer} chat={chat} setChat={setChat} ask={ask} busy={busy} active={false}/>
    </section>
   </div>:current&&<div className="tracking-layout"><section className="tracking-main">
      <div className={'transfer-status-card '+(current.status==='reconciled'?'arrived':'')}><span className="status-illustration">{current.status==='reconciled'?<CheckCheck size={38}/>:['information_required','delayed','manual_review','outcome_unknown'].includes(current.status)?<AlertCircle size={36}/>:<Send size={36}/>}</span><Status value={current.status}/><h2>{statusCopy[current.status]??label(current.status)}</h2><p>{current.receipt?`The provider recorded ${money(current.receipt.actual_recipient_minor,'INR')} for ${current.recipient.name}.`:current.status==='outcome_unknown'?'We’re checking the original request. No replacement transfer will be sent.':current.status==='information_required'?'Your provider needs purpose evidence before it can continue.':current.status==='cancelled'?`Source refund: ${current.transfer?.refund_status??'not yet confirmed'}.`:current.status==='manual_review'?'The evidence needs operator review. This case is still unresolved.':'Source funding and recipient delivery are tracked separately. We’ll only mark arrival when we have proof.'}
      </p><div className="transfer-amount-row"><div><span>You pay</span><strong>{money(current.transfer!.quote.source_total_minor)}</strong></div><ArrowRight size={24}/><div><span>{current.receipt?'Actually received':'Expected to receive'}</span><strong>{money(current.receipt?.actual_recipient_minor??current.transfer!.quote.recipient_minor,'INR')}</strong></div></div>
      {current.deadline_risk&&<div className="inline-note amber"><AlertCircle size={16}/>The requested deadline has passed. The transfer remains under review.</div>}
      {current.receipt&&<div className="receipt-actions"><span><FileCheck2 size={17}/>{current.receipt.reconciliation_status==='matched'?'Amounts match your approved quote':'Amount difference needs review'}</span><a className="secondary small" href={`/v1/remittance-transfers/${current.transfer!.id}/receipt`} download><Download size={15}/>Download receipt</a></div>}
      </div>
      {current.status==='information_required'&&<div className="document-request panel"><div className="document-icon"><FileText size={23}/></div><div><h3>Purpose of transfer</h3><p>{names[current.transfer!.provider_id]} requested a family support declaration. Review the exact document before sharing it.</p><button className="primary small" onClick={()=>void followup('documents')} disabled={!!busy}>Review document packet<ArrowRight size={16}/></button></div></div>}
      <div className="panel timeline-panel"><div className="panel-title"><h2>Every step, recorded</h2><span className="mini-label"><ShieldCheck size={14}/>Evidence timeline</span></div><div className="timeline">{current.events.filter(e=>!['quotes.requested','case.created'].includes(e.type)).map((event,index)=><div className="timeline-item" key={event.id}><span className={'timeline-icon '+(index===current.events.length-3?'latest':'')}><Check size={12}/></span><div><div className="timeline-title"><strong>{label(event.type.split('.').slice(-1)[0])}</strong><time>{date(event.timestamp)}</time></div><p>{event.message}</p></div></div>)}</div></div>
      <ConciergeBox answer={answer} chat={chat} setChat={setChat} ask={ask} busy={busy} active/>
    </section><aside className="tracking-aside"><div className="panel transfer-summary"><div className="panel-title"><h2>Transfer details</h2><ProviderIcon id={current.transfer!.provider_id}/></div><div className="summary-recipient"><div className="avatar recipient-avatar">{current.recipient.name.split(' ').map(n=>n[0]).join('')}</div><div><strong>{current.recipient.name}</strong><span>{current.recipient.bank} {current.recipient.account_mask}</span></div></div><dl><div><dt>Provider</dt><dd>{names[current.transfer!.provider_id]}</dd></div><div><dt>Transfer fee</dt><dd>{money(current.transfer!.quote.fee_minor)}</dd></div><div><dt>Exchange rate</dt><dd>1 USD = {current.transfer!.quote.effective_rate_decimal} INR</dd></div><div><dt>Deadline</dt><dd>{date(current.deadline_at)}</dd></div><div><dt>Purpose</dt><dd>{label(current.purpose)}</dd></div></dl><div className="reference"><span>PROVIDER REFERENCE</span><code>{current.transfer!.provider_transfer_ref??'Awaiting confirmation'}</code></div>{['funding_pending','processing','information_required','payout_pending','delayed','manual_review'].includes(current.status)&&!current.receipt&&<button className="secondary full" onClick={()=>void followup('cancel')} disabled={!!busy}>Request cancellation</button>}</div>
      <div className="simulation-card"><span className="eyebrow"><FlaskConical size={15}/>DEMO CONTROLS</span><h3>See what happens next.</h3><p>The simulator uses a frozen clock. Move time forward to follow provider events.</p><div className="demo-clock"><Clock3 size={16}/>{date(current.clock)}</div><div className="clock-buttons"><button className="secondary" onClick={()=>void advance(5)} disabled={!!busy}>+ 5 minutes</button><button className="primary" onClick={()=>void advance(1440)} disabled={!!busy}>+ 24 hours</button></div><small>All transfers and documents are synthetic.</small></div></aside></div>}
  </>}
  {page==='activity'&&<><div className="page-heading"><div><div className="eyebrow">FROM SENT TO SETTLED</div><h1>Transfer activity</h1><p>Every quote, decision, and arrival in one place.</p></div><button className="primary" onClick={()=>{setPage('send');setCurrent(null);setEditing(true);setConfirmed(false)}}><Plus size={17}/>New transfer</button></div><div className="activity-stats">{[['Total cases',boot?.cases.length??0],['Verified arrivals',boot?.cases.filter(c=>c.status==='reconciled').length??0],['Needs attention',boot?.cases.filter(c=>['information_required','manual_review','outcome_unknown'].includes(c.status)).length??0]].map(([l,v])=><div className="panel" key={l}><span>{l}</span><strong>{v}</strong></div>)}</div><div className="panel activity-list"><div className="panel-title"><h2>Your transfers</h2><button className="icon-button" aria-label="Refresh transfers" onClick={()=>void run('refresh',async()=>{await refresh()})}><RefreshCw size={17}/></button></div>{boot?.cases.length?boot.cases.map(c=><button className="activity-row" onClick={()=>void selectCase(c.id)} key={c.id}><span className="activity-direction"><ArrowUpRight size={21}/></span><div><strong>{recipients.find(r=>r.id===c.beneficiary_id)?.name}</strong><span>{date(c.created_at)} · USD to INR</span></div><Status value={c.status}/><strong>{c.source_budget_minor?money(c.source_budget_minor):money(c.target_required_minor??0,'INR')}</strong><ChevronRight size={18}/></button>):<div className="empty-state"><History size={32}/><h3>Your first transfer starts here</h3><p>Compare providers to create a transfer case.</p></div>}</div></>}
  {page==='recipients'&&<><div className="page-heading"><div><div className="eyebrow">FAMILIAR FACES. VERIFIED DETAILS.</div><h1>Your recipients</h1><p>Verified synthetic bank accounts for this USD → INR demo.</p></div><span className="pill"><ShieldCheck size={15}/>{recipients.length} verified recipients</span></div><div className="recipient-grid">{recipients.map(r=><div className="panel recipient-detail" key={r.id}><div className="recipient-detail-top"><div className="avatar large">{r.name.split(' ').map(n=>n[0]).join('')}</div><Status value={r.verification_status}/></div><h2>{r.name}</h2><p>{r.relationship} · {r.city}</p><dl><div><dt>Bank</dt><dd>{r.bank}</dd></div><div><dt>Account</dt><dd>{r.account_mask}</dd></div><div><dt>IFSC</dt><dd>{r.ifsc_mask}</dd></div><div><dt>Record version</dt><dd>{r.version}</dd></div></dl><button className="secondary full" onClick={()=>{setRecipientId(r.id);setCurrent(null);setEditing(true);setConfirmed(false);setPage('send')}}>Send to {r.name.split(' ')[0]}<ArrowRight size={17}/></button></div>)}</div></>}
  {page==='operations'&&overview&&<><div className="page-heading"><div><div className="eyebrow">OPERATOR WORKSPACE</div><h1>A clear view of the rails.</h1><p>Inspect case state, durable jobs, and provider evidence.</p></div><button className="secondary" onClick={()=>void loadOps()} disabled={!!busy}><RefreshCw size={16}/>Refresh</button></div><div className="ops-metrics">{[['Waiting on customer',overview.metrics.waiting_customer],['Waiting on provider',overview.metrics.waiting_provider],['Pending jobs',overview.metrics.pending_jobs],['Reconciled',overview.metrics.reconciled]].map(([l,v])=><div className="panel" key={l}><span>{l}</span><strong>{v}</strong></div>)}</div><div className="ops-toolbar"><div className="tabs">{['cases','jobs','events','tools'].map(t=><button key={t} onClick={()=>setOperatorTab(t)} className={operatorTab===t?'active':''}>{label(t)}</button>)}</div><div className="operator-clock"><Clock3 size={15}/>{date(overview.clock)}<button className="secondary small" onClick={()=>void advance(5)} disabled={!!busy}>+ 5m</button><button className="secondary small" onClick={()=>void advance(1440)} disabled={!!busy}>+ 24h</button></div></div><div className="panel ops-table">
    {operatorTab==='cases'&&<><div className="table-heading"><span>Case / recipient</span><span>State</span><span>Version</span><span>Deadline</span><span/></div>{overview.cases.map(c=><button className="table-row" key={c.id} onClick={()=>void selectCase(c.id)}><div><strong>{recipients.find(r=>r.id===c.beneficiary_id)?.name}</strong><code>{c.id}</code></div><Status value={c.status}/><span>v{c.version}</span><span>{date(c.deadline_at)}</span><ChevronRight size={16}/></button>)}</>}
    {operatorTab==='jobs'&&<><div className="table-heading"><span>Job</span><span>Status</span><span>Attempts</span><span>Scheduled</span><span/></div>{overview.jobs.filter(j=>j.kind!=='notify').slice(-30).reverse().map(j=><div className="table-row" key={j.id}><div><strong>{label(j.kind)}</strong><code>{j.id}</code>{j.last_error&&<small>{j.last_error}</small>}</div><Status value={j.status}/><span>{j.attempts}</span><span>{date(j.due_at)}</span><span/></div>)}</>}
    {operatorTab==='events'&&<><div className="table-heading"><span>Provider event</span><span>Status</span><span>Provider</span><span>Replay</span><span/></div>{overview.inbox.map(e=><div className="table-row" key={e.id}><code>{e.event_id}</code><Status value={e.status}/><span>{names[e.provider_id]}</span><span>{e.status==='deferred'?<button className="secondary small" onClick={()=>void run('replay',async()=>{await api(`/v1/operator/inbox/${e.id}/replay`,{},operatorToken);setOverview(await api<Overview>('/v1/operator/overview',undefined,operatorToken))})}>Replay</button>:'Recorded'}</span><span/></div>)}</>}
    {operatorTab==='tools'&&<><div className="table-heading"><span>Tool</span><span>Outcome</span><span>Latency</span><span>Mode</span><span/></div>{overview.tool_runs.map(t=><div className="table-row" key={t.id}><code>{t.tool_name}</code><Status value={t.outcome}/><span>{t.latency_ms} ms</span><span>Rules only · $0</span><span/></div>)}</>}
    {((operatorTab==='cases'&&!overview.cases.length)||(operatorTab==='events'&&!overview.inbox.length)||(operatorTab==='tools'&&!overview.tool_runs.length))&&<div className="empty-state"><Activity size={30}/><h3>No records yet</h3><p>Complete a transfer step to see its evidence here.</p></div>}
  </div><div className="ops-notes"><ShieldCheck size={17}/><span>Provider results are simulated. Approval and execution checks also apply to replayed work. Oldest queued job: {overview.metrics.oldest_queue_age_minutes} min.</span></div></>}
  </>}
  <footer><span><Logo small/>Thoughtfully across borders.</span><span>USD → INR · Mock providers · No real money moves</span></footer>
  </main></div>
  {toast&&<div className="toast" role="status"><CheckCircle2 size={19}/>{toast}<button aria-label="Dismiss notification" onClick={()=>setToast('')}><X size={16}/></button></div>}
  <dialog ref={dialog} className="review-dialog" onCancel={()=>setAction(null)}>{action&&<><div className="modal-header"><span className="eyebrow"><LockKeyhole size={14}/>YOUR APPROVAL, YOUR CONTROL</span><button className="icon-button" aria-label="Close review" onClick={()=>setAction(null)}><X size={21}/></button></div><h2>{action.type==='initiate'?'One last look before it goes.':action.type==='share_documents'?'Review your document packet':'Request a cancellation'}</h2><p className="modal-intro">{action.payload.effect}</p><div className="modal-recipient"><div className="avatar recipient-avatar">{action.payload.recipient.name.split(' ').map(n=>n[0]).join('')}</div><div><strong>{action.payload.recipient.name}</strong><span>{action.payload.recipient.bank} · {action.payload.recipient.account_mask}</span></div><ShieldCheck size={20}/></div><dl className="approval-details"><div><dt>Provider</dt><dd>{action.payload.provider_name} <small>Simulated</small></dd></div><div><dt>Total debit (USD)</dt><dd>{money(action.payload.quote.source_total_minor)}</dd></div><div><dt>Transfer fee included</dt><dd>{money(action.payload.quote.fee_minor)}</dd></div><div><dt>Exchange rate</dt><dd>1 USD = {action.payload.quote.effective_rate_decimal} INR</dd></div><div><dt>Recipient deduction included</dt><dd>{money(action.payload.quote.known_deduction_minor,'INR')}</dd></div><div><dt>Estimated delivery</dt><dd>{action.payload.quote.delivery_window.hours.join('–')} hours · Not guaranteed</dd></div><div className="approval-total"><dt>Expected recipient amount</dt><dd>{money(action.payload.quote.recipient_minor,'INR')}</dd></div></dl>
  {action.type==='share_documents'&&<div className="document-preview"><FileText size={22}/><div><strong>{action.payload.documents?.map(d=>d.name).join(', ')}</strong><p>Shared only with {action.payload.provider_name}: purpose-supporting evidence.</p><blockquote>{boot?.documents.find(d=>d.id==='doc_purpose_demo')?.content}</blockquote></div></div>}
  <div className="approval-expiry"><Clock3 size={14}/>Approval expires {date(action.expires_at)}. Material changes require a new review.</div><label className="checkbox-label approval-check"><input type="checkbox" checked={approvedCheck} onChange={e=>setApprovedCheck(e.target.checked)}/><span>{action.type==='initiate'?'I approve this exact simulated transfer to the verified recipient.':action.type==='share_documents'?'I approve sharing only this document with the named provider.':'I understand this requests cancellation and does not confirm it.'}</span></label>
  {error&&<div className="inline-note amber" role="alert">{error}</div>}
  <div className="modal-buttons"><button className="secondary" onClick={()=>setAction(null)}>Back to review</button><button className="primary" disabled={!approvedCheck||!!busy} onClick={()=>void approveAction()}>{busy==='approve'?<Loader2 className="spin" size={16}/>:<LockKeyhole size={16}/>} {action.type==='initiate'?'Approve & send':action.type==='share_documents'?'Approve sharing':'Approve request'}</button></div>
  {action.type==='initiate'&&<details className="scenario-details"><summary><FlaskConical size={14}/>Simulator scenario</summary><p>Choose a fixture to test the provider’s response. This only changes the simulator.</p><select aria-label="Simulator scenario" defaultValue={current?.transfer?.scenario} onChange={e=>void run('scenario',async()=>{let token=operatorToken;if(!token){const s=await api<{access_token:string}>('/v1/demo/session',{persona:'operator'});token=s.access_token;setOperatorToken(token)}await api(`/v1/operator/transfers/${action.payload.transfer_id}/scenario`,{scenario:e.target.value},token);notify('Simulator scenario updated.')})}>{['normal','timeout','missing_document','short_payment','delay','rejection','cancel_denied','malformed'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></details>}
  </>}</dialog>
  <dialog ref={helpDialog} className="review-dialog help-dialog" onCancel={()=>setHelp(false)}><div className="modal-header"><Logo small/><button className="icon-button" aria-label="Close about" onClick={()=>setHelp(false)}><X size={21}/></button></div><h2>A working journey. Simulated rails.</h2><p>Passage compares three fictional providers for transfers from the US to India. Customer identities, bank details, documents, fees, and exchange rates are synthetic.</p><div className="help-feature"><ShieldCheck/><div><strong>Review before every action</strong><p>Initiation, document sharing, and cancellation each need your approval.</p></div></div><div className="help-feature"><Clock3/><div><strong>Move the demo forward</strong><p>Advance the frozen clock from transfer tracking or the operations console.</p></div></div><div className="help-feature"><CheckCheck/><div><strong>Delivery needs evidence</strong><p>Source funding is separate from recipient credit. A verified receipt includes the amount and payout reference.</p></div></div><a href="/docs" target="_blank" rel="noreferrer" className="secondary full">Explore the API documentation<ExternalLink size={16}/></a></dialog>
 </div>
}
function ConciergeBox({answer,chat,setChat,ask,busy,active}:{answer:string;chat:string;setChat:(v:string)=>void;ask:(v:string)=>Promise<void>;busy:string;active:boolean}){return <div className="concierge-card"><div className="concierge-heading"><span className="sparkle-icon"><Sparkles size={19}/></span><div><strong>A little guidance, along the way.</strong><span>Your Passage concierge · Rules-based demo</span></div></div>{answer?<p className="concierge-answer" role="status">{answer}</p>:<p>{active?'Ask about your transfer’s evidence or the next step.':'I’ve compared the full cost and your deadline. Your recipient’s amount is what matters.'}</p>}<div className="suggestions">{(active?['What happens next?','Is delivery verified?']:['Which is fastest?','Is arrival guaranteed?']).map(q=><button key={q} disabled={!!busy} onClick={()=>void ask(q)}>{q}<ArrowUpRight size={13}/></button>)}</div><form onSubmit={e=>{e.preventDefault();if(chat.trim())void ask(chat)}}><input aria-label="Ask the concierge" placeholder="Ask about your transfer…" value={chat} onChange={e=>setChat(e.target.value)} maxLength={2000}/><button type="submit" aria-label="Send question" disabled={!chat.trim()||!!busy}>{busy==='chat'?<Loader2 className="spin" size={16}/>:<ArrowUpRight size={19}/>}</button></form></div>}
createRoot(document.getElementById('root')!).render(<App/>);
